name: Far Cry VR Automated Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Far Cry VR
    runs-on: windows-2022

    permissions: write-all

    env:
      PYTHONUTF8: 1

    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v3
        with:
          msbuild-architecture: x86

      - name: Build CryGame and the d3d9.dll proxy
        working-directory: "Sources/CryGame C++/Solution1"
        run: msbuild Solution1.sln /p:Configuration=Release -m

      - name: Create installer
        working-directory: installer
        shell: cmd
        run: create_installer.bat

      - name: Move 'latest' tag to this commit
        if: github.ref_type == 'branch'
        shell: bash
        run: |
          git tag -f latest
          git push -f origin latest

      - name: Update Github dev release
        if: github.ref_type == 'branch'
        uses: softprops/action-gh-release@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: latest
          target_commitish: ${{ github.sha }}
          prerelease: true
          make_latest: false
          name: "FarCry VR development build"
          files: |
            installer/farcry-vrmod*.exe

      - name: Create tagged Github release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v3
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          name: "FarCry VR release ${{ github.ref_name }}"
          files: |
            installer/farcry-vrmod*.exe
